/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BlobKzgVerifierInterface extends Interface {
  getFunction(
    nameOrSignature: "currentBlobBaseFee" | "getBlobHash" | "verifyBlob"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "BlobVerified"): EventFragment;

  encodeFunctionData(
    functionFragment: "currentBlobBaseFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBlobHash",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyBlob",
    values: [
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "currentBlobBaseFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBlobHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyBlob", data: BytesLike): Result;
}

export namespace BlobVerifiedEvent {
  export type InputTuple = [
    versionedHash: BytesLike,
    batchId: BytesLike,
    blobIndex: BigNumberish
  ];
  export type OutputTuple = [
    versionedHash: string,
    batchId: string,
    blobIndex: bigint
  ];
  export interface OutputObject {
    versionedHash: string;
    batchId: string;
    blobIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BlobKzgVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): BlobKzgVerifier;
  waitForDeployment(): Promise<this>;

  interface: BlobKzgVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  currentBlobBaseFee: TypedContractMethod<[], [bigint], "view">;

  getBlobHash: TypedContractMethod<[index: BigNumberish], [string], "view">;

  verifyBlob: TypedContractMethod<
    [
      blobIndex: BigNumberish,
      openingPoint: BytesLike,
      claimedValue: BytesLike,
      commitment: BytesLike,
      proof: BytesLike,
      batchId: BytesLike,
      maxBlobBaseFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "currentBlobBaseFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBlobHash"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "verifyBlob"
  ): TypedContractMethod<
    [
      blobIndex: BigNumberish,
      openingPoint: BytesLike,
      claimedValue: BytesLike,
      commitment: BytesLike,
      proof: BytesLike,
      batchId: BytesLike,
      maxBlobBaseFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BlobVerified"
  ): TypedContractEvent<
    BlobVerifiedEvent.InputTuple,
    BlobVerifiedEvent.OutputTuple,
    BlobVerifiedEvent.OutputObject
  >;

  filters: {
    "BlobVerified(bytes32,bytes32,uint256)": TypedContractEvent<
      BlobVerifiedEvent.InputTuple,
      BlobVerifiedEvent.OutputTuple,
      BlobVerifiedEvent.OutputObject
    >;
    BlobVerified: TypedContractEvent<
      BlobVerifiedEvent.InputTuple,
      BlobVerifiedEvent.OutputTuple,
      BlobVerifiedEvent.OutputObject
    >;
  };
}
