/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IBlobSubmissionInterface extends Interface {
  getFunction(
    nameOrSignature: "submitZkValidityProofWithBlob"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "BlobSubmitted"): EventFragment;

  encodeFunctionData(
    functionFragment: "submitZkValidityProofWithBlob",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "submitZkValidityProofWithBlob",
    data: BytesLike
  ): Result;
}

export namespace BlobSubmittedEvent {
  export type InputTuple = [
    windowIndex: BigNumberish,
    blobHash: BytesLike,
    blobDataHash: BytesLike
  ];
  export type OutputTuple = [
    windowIndex: bigint,
    blobHash: string,
    blobDataHash: string
  ];
  export interface OutputObject {
    windowIndex: bigint;
    blobHash: string;
    blobDataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IBlobSubmission extends BaseContract {
  connect(runner?: ContractRunner | null): IBlobSubmission;
  waitForDeployment(): Promise<this>;

  interface: IBlobSubmissionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  submitZkValidityProofWithBlob: TypedContractMethod<
    [
      proof: BytesLike,
      publicInputs: BytesLike,
      expectedBlobHash: BytesLike,
      blobDataHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "submitZkValidityProofWithBlob"
  ): TypedContractMethod<
    [
      proof: BytesLike,
      publicInputs: BytesLike,
      expectedBlobHash: BytesLike,
      blobDataHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BlobSubmitted"
  ): TypedContractEvent<
    BlobSubmittedEvent.InputTuple,
    BlobSubmittedEvent.OutputTuple,
    BlobSubmittedEvent.OutputObject
  >;

  filters: {
    "BlobSubmitted(uint256,bytes32,bytes32)": TypedContractEvent<
      BlobSubmittedEvent.InputTuple,
      BlobSubmittedEvent.OutputTuple,
      BlobSubmittedEvent.OutputObject
    >;
    BlobSubmitted: TypedContractEvent<
      BlobSubmittedEvent.InputTuple,
      BlobSubmittedEvent.OutputTuple,
      BlobSubmittedEvent.OutputObject
    >;
  };
}
