/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IZkAggregatorVerifier,
  IZkAggregatorVerifierInterface,
} from "../../interfaces/IZkAggregatorVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "publicInputs",
        type: "bytes",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "valid",
        type: "bool",
      },
      {
        internalType: "bytes32",
        name: "stfCommitment",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "programVKey",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "policyHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "proverSetDigest",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IZkAggregatorVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IZkAggregatorVerifierInterface {
    return new Interface(_abi) as IZkAggregatorVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IZkAggregatorVerifier {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IZkAggregatorVerifier;
  }
}
