/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  BlobKzgVerifier,
  BlobKzgVerifierInterface,
} from "../../../../contracts/src/blob/BlobKzgVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "actual",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maximum",
        type: "uint256",
      },
    ],
    name: "BlobBaseFeeExceedsMax",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "BlobHashZero",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "claim",
        type: "uint256",
      },
    ],
    name: "ClaimOutOfField",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "provided",
        type: "uint256",
      },
    ],
    name: "InvalidCommitmentLength",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "provided",
        type: "uint256",
      },
    ],
    name: "InvalidProofLength",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "versionedHash",
        type: "bytes32",
      },
    ],
    name: "PointEvaluationFailed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "point",
        type: "uint256",
      },
    ],
    name: "PointOutOfField",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "versionedHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "batchId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "blobIndex",
        type: "uint256",
      },
    ],
    name: "BlobVerified",
    type: "event",
  },
  {
    inputs: [],
    name: "currentBlobBaseFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "getBlobHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "blobIndex",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "openingPoint",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "claimedValue",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "commitment",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "bytes32",
        name: "batchId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "maxBlobBaseFee",
        type: "uint256",
      },
    ],
    name: "verifyBlob",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523460155761032c908161001a8239f35b5f80fdfe6080806040526004361015610012575f80fd5b5f3560e01c9081634ebf82e51461028a575080636aea51571461027057638a79a03b1461003d575f80fd5b3461026c5760e036600319011261026c5760043560243560443560643567ffffffffffffffff811161026c576100779036906004016102a6565b919060843567ffffffffffffffff811161026c576100999036906004016102a6565b92909160c435804a116102565750603085036102435760308403610230577f73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff0000000186101561021d577f73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff0000000182101561020a5786499586156101f75760808588955f9897888a9961015797604051998a9860208a019c8d5260408a01526060890152868801378501918483018a815237010185815203601f1981018352826102d4565b5190600a61c350fa3d156101f2573d67ffffffffffffffff81116101de576040519061018d601f8201601f1916602001836102d4565b81525f60203d92013e5b156101cc576040519182527ffb7268d8062cd023a10af92ec4ffd360338518613313b2587aa326e7c735c440602060a43593a3005b636c6fa38360e11b5f5260045260245ffd5b634e487b7160e01b5f52604160045260245ffd5b610197565b87639cbca63560e01b5f5260045260245ffd5b506304b05bf160e11b5f5260045260245ffd5b8563376e868760e11b5f5260045260245ffd5b83639968ccf160e01b5f5260045260245ffd5b84639ed0fa1d60e01b5f5260045260245ffd5b639f08961560e01b5f524a60045260245260445ffd5b5f80fd5b3461026c575f36600319011261026c5760206040514a8152f35b3461026c57602036600319011261026c57602090600435498152f35b9181601f8401121561026c5782359167ffffffffffffffff831161026c576020838186019501011161026c57565b90601f8019910116810190811067ffffffffffffffff8211176101de5760405256fea2646970667358221220a397d5734f5e5fff930a0cc74a61f777bcddd4c23f01612965cf793a8ccf72ae64736f6c63430008220033";

type BlobKzgVerifierConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BlobKzgVerifierConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BlobKzgVerifier__factory extends ContractFactory {
  constructor(...args: BlobKzgVerifierConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      BlobKzgVerifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): BlobKzgVerifier__factory {
    return super.connect(runner) as BlobKzgVerifier__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BlobKzgVerifierInterface {
    return new Interface(_abi) as BlobKzgVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BlobKzgVerifier {
    return new Contract(address, _abi, runner) as unknown as BlobKzgVerifier;
  }
}
