/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  BlobVerifierHarness,
  BlobVerifierHarnessInterface,
} from "../../../../contracts/src/blob/BlobVerifierHarness";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "expected",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "actual",
        type: "bytes32",
      },
    ],
    name: "BlobHashMismatch",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "expected",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "actual",
        type: "bytes32",
      },
    ],
    name: "BlobHashMismatch",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "hash",
        type: "bytes32",
      },
    ],
    name: "InvalidVersionedHash",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "hash",
        type: "bytes32",
      },
    ],
    name: "InvalidVersionedHash",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "NoBlobAtIndex",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "NoBlobAtIndex",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "getBlobHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "hash",
        type: "bytes32",
      },
    ],
    name: "validateVersionByte",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "expected",
        type: "bytes32",
      },
    ],
    name: "verifyBlobHash",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523460155761010a908161001a8239f35b5f80fdfe608060405260043610156010575f80fd5b5f3560e01c806306be1bd31460865780634a3385f214605657634ebf82e5146036575f80fd5b3460525760203660031901126052576020604051600435498152f35b5f80fd5b34605257602036600319011260525760043560018160f81c03607457005b6351515da360e01b5f5260045260245ffd5b346052576040366003190112605257600435602435814991821560c35781830360ab57005b6339fe9a7b60e11b5f5260045260245260445260645ffd5b6227563160e11b5f5260045260245ffdfea26469706673582212203a0c3311c3cefd5e1f00f5b75866b46e46a0bd2fc47b844ff5c0be2dd7e10e3064736f6c63430008220033";

type BlobVerifierHarnessConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BlobVerifierHarnessConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BlobVerifierHarness__factory extends ContractFactory {
  constructor(...args: BlobVerifierHarnessConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      BlobVerifierHarness & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): BlobVerifierHarness__factory {
    return super.connect(runner) as BlobVerifierHarness__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BlobVerifierHarnessInterface {
    return new Interface(_abi) as BlobVerifierHarnessInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BlobVerifierHarness {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as BlobVerifierHarness;
  }
}
