/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  Halo2Verifier,
  Halo2VerifierInterface,
} from "../../../../contracts/src/zk/Halo2Verifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bool",
        name: "_mockMode",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "MIN_PROOF_LENGTH",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "NUM_INSTANCES",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "mockMode",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "uint256[]",
        name: "instances",
        type: "uint256[]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "valid",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60a034606557601f61026838819003918201601f19168301916001600160401b038311848410176069578084926020946040528339810103126065575180151581036065576080526040516101ea908161007e8239608051818181605f015261017e0152f35b5f80fd5b634e487b7160e01b5f52604160045260245ffdfe6080806040526004361015610012575f80fd5b5f3560e01c9081630820bd7714610151575080630fb03ab6146101355780631e8e1e13146100885763751222c914610048575f80fd5b34610084575f3660031901126100845760206040517f000000000000000000000000000000000000000000000000000000000000000015158152f35b5f80fd5b346100845760403660031901126100845760043567ffffffffffffffff811161008457366023820112156100845780600401359067ffffffffffffffff8211610084573660248383010111610084576024359067ffffffffffffffff821161008457366023830112156100845781600401359067ffffffffffffffff8211610084573660248360051b850101116100845760209360248061012b9501920161016a565b6040519015158152f35b34610084575f3660031901126100845760206040516105c08152f35b34610084575f3660031901126100845780600260209252f35b506105c09150106101af576002036101ab577f00000000000000000000000000000000000000000000000000000000000000006101a657600190565b600190565b5f90565b505f9056fea26469706673582212209d1e777d6ee2327264d19d720bff7ec29efaa88a93de7e2a545489a0473e6e9c64736f6c63430008220033";

type Halo2VerifierConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: Halo2VerifierConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Halo2Verifier__factory extends ContractFactory {
  constructor(...args: Halo2VerifierConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _mockMode: boolean,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_mockMode, overrides || {});
  }
  override deploy(
    _mockMode: boolean,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_mockMode, overrides || {}) as Promise<
      Halo2Verifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Halo2Verifier__factory {
    return super.connect(runner) as Halo2Verifier__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Halo2VerifierInterface {
    return new Interface(_abi) as Halo2VerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): Halo2Verifier {
    return new Contract(address, _abi, runner) as unknown as Halo2Verifier;
  }
}
