/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IZkAdapter, IZkAdapterInterface } from "../IZkAdapter";

const _abi = [
  {
    inputs: [],
    name: "expectedProofLength",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "proofSystemId",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "bytes32[]",
        name: "publicInputs",
        type: "bytes32[]",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "valid",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IZkAdapter__factory {
  static readonly abi = _abi;
  static createInterface(): IZkAdapterInterface {
    return new Interface(_abi) as IZkAdapterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IZkAdapter {
    return new Contract(address, _abi, runner) as unknown as IZkAdapter;
  }
}
