// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "../src/zk/Groth16Verifier.sol";
import "../src/zk/Groth16ZkAdapter.sol";
import "../src/IZkAdapter.sol";

/// @title Groth16RealVerifierTest
/// @notice Tests the real Groth16Verifier with a genuine BN254 pairing proof.
///         The fixture is generated by: node scripts/generate-groth16-fixture.mjs
///
///         Run with: forge test --match-contract Groth16RealVerifierTest -v
contract Groth16RealVerifierTest is Test {
    bytes32 constant PROGRAM_VKEY = keccak256("integration-program-vkey");
    bytes32 constant POLICY_HASH = keccak256("integration-policy-hash");

    Groth16Verifier verifier;
    Groth16ZkAdapter adapter;

    // Fixture data
    uint256[2] pA;
    uint256[2][2] pB;
    uint256[2] pC;
    uint256 stfCommitment;
    uint256 proverSetDigest;

    function setUp() public {
        verifier = new Groth16Verifier();
        adapter = new Groth16ZkAdapter(address(verifier), PROGRAM_VKEY, POLICY_HASH);

        string memory json = vm.readFile("test/fixtures/groth16-proof-fixture.json");

        // Parse pA
        pA[0] = vm.parseJsonUint(json, ".proof.pA[0]");
        pA[1] = vm.parseJsonUint(json, ".proof.pA[1]");

        // Parse pB (note: snarkjs Groth16 pB is [2][2])
        pB[0][0] = vm.parseJsonUint(json, ".proof.pB[0][0]");
        pB[0][1] = vm.parseJsonUint(json, ".proof.pB[0][1]");
        pB[1][0] = vm.parseJsonUint(json, ".proof.pB[1][0]");
        pB[1][1] = vm.parseJsonUint(json, ".proof.pB[1][1]");

        // Parse pC
        pC[0] = vm.parseJsonUint(json, ".proof.pC[0]");
        pC[1] = vm.parseJsonUint(json, ".proof.pC[1]");

        // Parse public outputs
        stfCommitment = vm.parseJsonUint(json, ".publicOutputs.stfCommitment");
        proverSetDigest = vm.parseJsonUint(json, ".publicOutputs.proverSetDigest");
    }

    // ── Helper ─────────────────────────────────────────────────────────────

    function _encodeAdapterProof() internal view returns (bytes memory) {
        return abi.encode(pA, pB, pC, stfCommitment, proverSetDigest);
    }

    // ── 1. Real verifier accepts genuine proof ─────────────────────────────

    function test_realVerifierAcceptsValidProof() public view {
        bool valid = verifier.verifyProof(pA, pB, pC, [stfCommitment, proverSetDigest]);
        assertTrue(valid, "Real Groth16 verifier must accept a valid BN254 pairing proof");
    }

    // ── 2. Real verifier rejects wrong stfCommitment ───────────────────────

    function test_realVerifierRejectsWrongStfCommitment() public view {
        bool valid = verifier.verifyProof(pA, pB, pC, [stfCommitment ^ 1, proverSetDigest]);
        assertFalse(valid, "Real verifier must reject proof with wrong stfCommitment");
    }

    // ── 3. Real verifier rejects wrong proverSetDigest ─────────────────────

    function test_realVerifierRejectsWrongDigest() public view {
        bool valid = verifier.verifyProof(pA, pB, pC, [stfCommitment, proverSetDigest ^ 1]);
        assertFalse(valid, "Real verifier must reject proof with wrong proverSetDigest");
    }

    // ── 4. Real verifier rejects corrupted proof point ─────────────────────

    function test_realVerifierRejectsCorruptedProof() public view {
        uint256[2] memory badA = [pA[0] ^ 1, pA[1]];
        bool valid = verifier.verifyProof(badA, pB, pC, [stfCommitment, proverSetDigest]);
        assertFalse(valid, "Real verifier must reject corrupted proof point");
    }

    // ── 5. Adapter agg path accepts valid proof ────────────────────────────

    function test_adapterAggPathAcceptsValidProof() public view {
        bytes memory proof = _encodeAdapterProof();
        (bool valid, bytes32 stf, bytes32 vkey, bytes32 policy, bytes32 digest) =
            adapter.verify(proof, new bytes(0));

        assertTrue(valid, "Adapter must accept valid proof through real verifier");
        assertEq(stf, bytes32(stfCommitment));
        assertEq(vkey, PROGRAM_VKEY);
        assertEq(policy, POLICY_HASH);
        assertEq(digest, bytes32(proverSetDigest));
    }

    // ── 6. Adapter thin path accepts valid proof ───────────────────────────

    function test_adapterThinPathAcceptsValidProof() public view {
        bytes memory proof = _encodeAdapterProof();
        bytes32[] memory pubInputs = new bytes32[](0);
        bool valid = IZkAdapter(address(adapter)).verify(proof, pubInputs);
        assertTrue(valid, "Thin verify path must accept valid proof");
    }

    // ── 7. Adapter rejects corrupted proof ─────────────────────────────────

    function test_adapterRejectsCorruptedProofViaRealVerifier() public {
        // Corrupt pA
        uint256[2] memory badA = [pA[0] ^ 1, pA[1]];
        bytes memory proof = abi.encode(badA, pB, pC, stfCommitment, proverSetDigest);

        vm.expectRevert(Groth16ZkAdapter.ProofInvalid.selector);
        adapter.verify(proof, new bytes(0));
    }

    // ── 8. Adapter rejects wrong instances ─────────────────────────────────

    function test_adapterRejectsWrongInstancesViaRealVerifier() public {
        bytes memory proof = abi.encode(pA, pB, pC, stfCommitment ^ 1, proverSetDigest);

        vm.expectRevert(Groth16ZkAdapter.ProofInvalid.selector);
        adapter.verify(proof, new bytes(0));
    }
}
