// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "../src/PlonkVerifierV2.sol";
import "../src/zk/PlonkZkAdapter.sol";
import "../src/IZkAdapter.sol";

/// @title PlonkRealVerifierTest
/// @notice Tests the real PlonkVerifierV2 with a genuine BN254 pairing proof.
///         The fixture is generated by: node scripts/generate-plonk-fixture.mjs
///
///         Run with: forge test --match-contract PlonkRealVerifierTest -v
contract PlonkRealVerifierTest is Test {
    bytes32 constant PROGRAM_VKEY = keccak256("integration-program-vkey");
    bytes32 constant POLICY_HASH = keccak256("integration-policy-hash");

    PlonkVerifierV2 verifier;
    PlonkZkAdapter adapter;

    // Fixture data
    uint256[24] proofWords;
    uint256 stfCommitment;
    uint256 proverSetDigest;

    function setUp() public {
        verifier = new PlonkVerifierV2();
        adapter = new PlonkZkAdapter(address(verifier), PROGRAM_VKEY, POLICY_HASH);

        string memory json = vm.readFile("test/fixtures/plonk-proof-fixture.json");

        // Parse 24 proof words
        for (uint256 i = 0; i < 24; i++) {
            string memory key = string.concat(".proof.words[", vm.toString(i), "]");
            proofWords[i] = vm.parseJsonUint(json, key);
        }

        stfCommitment = vm.parseJsonUint(json, ".publicOutputs.stfCommitment");
        proverSetDigest = vm.parseJsonUint(json, ".publicOutputs.proverSetDigest");
    }

    // ── Helper ─────────────────────────────────────────────────────────────

    function _encodeAdapterProof() internal view returns (bytes memory) {
        return abi.encode(proofWords, stfCommitment, proverSetDigest);
    }

    // ── 1. Real verifier accepts genuine proof ─────────────────────────────

    function test_realVerifierAcceptsValidProof() public view {
        bool valid = verifier.verifyProof(proofWords, [stfCommitment, proverSetDigest]);
        assertTrue(valid, "Real Plonk verifier must accept a valid BN254 pairing proof");
    }

    // ── 2. Real verifier rejects wrong stfCommitment ───────────────────────

    function test_realVerifierRejectsWrongStfCommitment() public view {
        bool valid = verifier.verifyProof(proofWords, [stfCommitment ^ 1, proverSetDigest]);
        assertFalse(valid, "Real verifier must reject proof with wrong stfCommitment");
    }

    // ── 3. Real verifier rejects wrong proverSetDigest ─────────────────────

    function test_realVerifierRejectsWrongDigest() public view {
        bool valid = verifier.verifyProof(proofWords, [stfCommitment, proverSetDigest ^ 1]);
        assertFalse(valid, "Real verifier must reject proof with wrong proverSetDigest");
    }

    // ── 4. Real verifier rejects corrupted proof word ──────────────────────

    function test_realVerifierRejectsCorruptedProof() public view {
        uint256[24] memory badWords;
        for (uint256 i = 0; i < 24; i++) {
            badWords[i] = proofWords[i];
        }
        badWords[0] ^= 1; // flip one bit in first word

        bool valid = verifier.verifyProof(badWords, [stfCommitment, proverSetDigest]);
        assertFalse(valid, "Real verifier must reject corrupted proof");
    }

    // ── 5. Adapter agg path accepts valid proof ────────────────────────────

    function test_adapterAggPathAcceptsValidProof() public view {
        bytes memory proof = _encodeAdapterProof();
        (bool valid, bytes32 stf, bytes32 vkey, bytes32 policy, bytes32 digest) =
            adapter.verify(proof, new bytes(0));

        assertTrue(valid, "Adapter must accept valid proof through real verifier");
        assertEq(stf, bytes32(stfCommitment));
        assertEq(vkey, PROGRAM_VKEY);
        assertEq(policy, POLICY_HASH);
        assertEq(digest, bytes32(proverSetDigest));
    }

    // ── 6. Adapter thin path accepts valid proof ───────────────────────────

    function test_adapterThinPathAcceptsValidProof() public view {
        bytes memory proof = _encodeAdapterProof();
        bytes32[] memory pubInputs = new bytes32[](0);
        bool valid = IZkAdapter(address(adapter)).verify(proof, pubInputs);
        assertTrue(valid, "Thin verify path must accept valid proof");
    }

    // ── 7. Adapter rejects corrupted proof ─────────────────────────────────

    function test_adapterRejectsCorruptedProofViaRealVerifier() public {
        uint256[24] memory badWords;
        for (uint256 i = 0; i < 24; i++) {
            badWords[i] = proofWords[i];
        }
        badWords[0] ^= 1;
        bytes memory proof = abi.encode(badWords, stfCommitment, proverSetDigest);

        vm.expectRevert(PlonkZkAdapter.ProofInvalid.selector);
        adapter.verify(proof, new bytes(0));
    }

    // ── 8. Adapter rejects wrong instances ─────────────────────────────────

    function test_adapterRejectsWrongInstancesViaRealVerifier() public {
        bytes memory proof = abi.encode(proofWords, stfCommitment ^ 1, proverSetDigest);

        vm.expectRevert(PlonkZkAdapter.ProofInvalid.selector);
        adapter.verify(proof, new bytes(0));
    }
}
