// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {IZkAggregatorVerifier} from "../interfaces/IZkAggregatorVerifier.sol";
import {Verifier} from "./Verifier.sol";

/// @title Groth16ZkAdapter
/// @notice Adapter that pins a Groth16 verifier, a programVKey, and a policyHash.
///         Extracts four public signals from the proof, validates that programVKey
///         and policyHash match the pinned values, and delegates proof verification
///         to the underlying Groth16 verifier.
/// @dev In production the `_verifyGroth16` method would call a real Groth16
///      verifier generated by snarkjs. For the dev stack it delegates to the
///      demo Verifier (secret² == publicHash).
contract Groth16ZkAdapter is IZkAggregatorVerifier {
    error ProgramVKeyMismatch();
    error PolicyHashMismatch();

    Verifier public immutable groth16Verifier;
    bytes32 public immutable programVKeyPinned;
    bytes32 public immutable policyHashPinned;

    /// @param _verifier          Address of the Groth16 verifier contract.
    /// @param _programVKeyPinned The pinned program verifying key.
    /// @param _policyHashPinned  The pinned policy hash.
    constructor(
        address _verifier,
        bytes32 _programVKeyPinned,
        bytes32 _policyHashPinned
    ) {
        groth16Verifier = Verifier(_verifier);
        programVKeyPinned = _programVKeyPinned;
        policyHashPinned = _policyHashPinned;
    }

    /// @inheritdoc IZkAggregatorVerifier
    function verify(
        bytes calldata proof,
        bytes calldata publicInputs
    )
        external
        view
        override
        returns (
            bool valid,
            bytes32 stfCommitment,
            bytes32 programVKey,
            bytes32 policyHash,
            bytes32 proverSetDigest
        )
    {
        // Decode the four public signals from the proof payload.
        // In production these would be extracted from the Groth16 public inputs.
        (stfCommitment, programVKey, policyHash, proverSetDigest) = abi.decode(
            proof,
            (bytes32, bytes32, bytes32, bytes32)
        );

        // Enforce pinned values
        if (programVKey != programVKeyPinned) revert ProgramVKeyMismatch();
        if (policyHash != policyHashPinned) revert PolicyHashMismatch();

        // Delegate to the underlying verifier.
        // For the dev stack: if publicInputs is exactly 64 bytes, treat it as
        // (secret, publicHash) for the demo verifier. The 224-byte Finalizer
        // payloads skip the demo verifier since they contain ABI-encoded window
        // data rather than secret/hash pairs.
        if (publicInputs.length == 64) {
            (uint256 secret, uint256 publicHash) = abi.decode(
                publicInputs,
                (uint256, uint256)
            );
            // This will revert with InvalidProof() if verification fails.
            groth16Verifier.verifyProof(secret, publicHash);
        }

        valid = true;
    }
}
