// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {IZkAggregatorVerifier} from "../interfaces/IZkAggregatorVerifier.sol";
import {Verifier} from "./Verifier.sol";

/// @title Groth16ZkAdapter
/// @notice Adapter that pins a Groth16 verifier, a programVKey, and a policyHash.
///         Extracts four public signals from the proof, validates that programVKey
///         and policyHash match the pinned values, and delegates proof verification
///         to the underlying Groth16 verifier.
/// @dev DEV-ONLY — This adapter does NOT perform real Groth16 verification for
///      224-byte (Finalizer) payloads. It only validates pinned values and always
///      returns valid=true for the Finalizer path. In production, replace the
///      verify() implementation with a real Groth16 verifier generated by snarkjs
///      that verifies the outer proof cryptographically.
///      The dev stack guard `block.chainid == 31337` prevents accidental deployment
///      to non-Hardhat networks.
contract Groth16ZkAdapter is IZkAggregatorVerifier {
    error ProgramVKeyMismatch();
    error PolicyHashMismatch();

    Verifier public immutable groth16Verifier;
    bytes32 public immutable programVKeyPinned;
    bytes32 public immutable policyHashPinned;

    /// @param _verifier          Address of the Groth16 verifier contract.
    /// @param _programVKeyPinned The pinned program verifying key.
    /// @param _policyHashPinned  The pinned policy hash.
    constructor(
        address _verifier,
        bytes32 _programVKeyPinned,
        bytes32 _policyHashPinned
    ) {
        require(block.chainid == 31337, "dev-only adapter");
        groth16Verifier = Verifier(_verifier);
        programVKeyPinned = _programVKeyPinned;
        policyHashPinned = _policyHashPinned;
    }

    /// @inheritdoc IZkAggregatorVerifier
    function verify(
        bytes calldata proof,
        bytes calldata publicInputs
    )
        external
        view
        override
        returns (
            bool valid,
            bytes32 stfCommitment,
            bytes32 programVKey,
            bytes32 policyHash,
            bytes32 proverSetDigest
        )
    {
        // Decode the four public signals from the proof payload.
        // In production these would be extracted from the Groth16 public inputs.
        (stfCommitment, programVKey, policyHash, proverSetDigest) = abi.decode(
            proof,
            (bytes32, bytes32, bytes32, bytes32)
        );

        // Enforce pinned values
        if (programVKey != programVKeyPinned) revert ProgramVKeyMismatch();
        if (policyHash != policyHashPinned) revert PolicyHashMismatch();

        // Delegate to the underlying verifier.
        // DEV-ONLY: For 224-byte Finalizer payloads the demo verifier is skipped.
        // In production, ALL code paths MUST perform cryptographic verification.
        // The pinned-value checks above are necessary but NOT sufficient for security.
        if (publicInputs.length == 64) {
            (uint256 secret, uint256 publicHash) = abi.decode(
                publicInputs,
                (uint256, uint256)
            );
            // This will revert with InvalidProof() if verification fails.
            groth16Verifier.verifyProof(secret, publicHash);
        }

        valid = true;
    }
}
