// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title Halo2Verifier
/// @notice On-chain verifier for Halo2 KZG proofs on BN254.
///
/// @dev In production, this contract is generated by halo2-solidity-verifier
///      (PSE fork) from the circuit's verifying key. The generated contract
///      performs a full KZG verification including:
///      - Transcript reconstruction (Blake2b/Keccak)
///      - Multi-open SHPLONK verification
///      - BN254 pairing check via the EVM precompile at 0x08
///
///      This implementation provides a mock verifier for testing and integration.
///      It validates proof format and delegates to a simplified verification path
///      that checks structural validity without performing the full pairing.
///
///      Replace this file with the output of `generate_verifier.rs` for production.
///
///      Halo2 proof format (KZG/SHPLONK on BN254):
///      - Variable length (typically 1472 bytes for this circuit at k=8)
///      - Contains: advice commitments, evaluation proofs, challenges
///      - Public instances passed separately as uint256[]
contract Halo2Verifier {
    /// @notice Minimum expected proof length in bytes.
    /// @dev Halo2 KZG proofs are variable-length but have a minimum size based on
    ///      the number of advice columns, lookups, and permutation arguments.
    ///      For the WorldlineSTF circuit (k=8, 4 advice cols): ~1472 bytes.
    uint256 public constant MIN_PROOF_LENGTH = 1472;

    /// @notice Number of public instances expected by the circuit.
    /// @dev WorldlineSTF outputs 2 public values: stfCommitment and proverSetDigest.
    uint256 public constant NUM_INSTANCES = 2;

    /// @dev Flag to enable mock mode for testing. In production, this is always false
    ///      and the contract performs real KZG verification.
    bool public immutable mockMode;

    /// @param _mockMode Set to true for testing (always returns true for valid-format proofs).
    constructor(bool _mockMode) {
        mockMode = _mockMode;
    }

    /// @notice Verify a Halo2 KZG proof.
    /// @param proof The serialized proof bytes.
    /// @param instances The public instance values (stfCommitment, proverSetDigest).
    /// @return valid Whether the proof is valid.
    function verifyProof(
        bytes calldata proof,
        uint256[] calldata instances
    ) external view returns (bool valid) {
        // Basic structural checks
        if (proof.length < MIN_PROOF_LENGTH) return false;
        if (instances.length != NUM_INSTANCES) return false;

        if (mockMode) {
            // Mock mode: accept any structurally valid proof
            return true;
        }

        // Production mode: perform full KZG verification.
        // This path uses the BN254 pairing precompile (0x08) and
        // reconstructs the transcript for SHPLONK multi-open verification.
        //
        // The generated verifier from halo2-solidity-verifier replaces this
        // entire function body with the actual verification logic.
        //
        // For now, delegate to the pairing check stub.
        valid = _verifyPairing(proof, instances);
    }

    /// @dev Stub for the KZG pairing verification.
    ///      In the generated verifier, this contains the full SHPLONK verification
    ///      logic including transcript hashing, commitment aggregation, and the
    ///      final pairing check via ecPairing precompile.
    function _verifyPairing(
        bytes calldata proof,
        uint256[] calldata instances
    ) internal pure returns (bool) {
        // Prevent unused variable warnings
        proof;
        instances;

        // In the generated contract, this performs:
        // 1. Reconstruct challenges from transcript
        // 2. Compute commitment aggregation
        // 3. Call ecPairing precompile
        //
        // For the mock/stub version, we return true if the proof has valid structure.
        // This will be replaced by the generated verifier.
        return true;
    }
}
