/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface Groth16ZkAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PROD_PROOF_MIN_LEN"
      | "expectedProofLength"
      | "policyHashPinned"
      | "programVKeyPinned"
      | "proofSystemId"
      | "verifierAddress"
      | "verify(bytes,bytes32[])"
      | "verify(bytes,bytes)"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "PROD_PROOF_MIN_LEN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "expectedProofLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "policyHashPinned",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "programVKeyPinned",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proofSystemId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifierAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verify(bytes,bytes32[])",
    values: [BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "verify(bytes,bytes)",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "PROD_PROOF_MIN_LEN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expectedProofLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "policyHashPinned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "programVKeyPinned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proofSystemId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifierAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verify(bytes,bytes32[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verify(bytes,bytes)",
    data: BytesLike
  ): Result;
}

export interface Groth16ZkAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): Groth16ZkAdapter;
  waitForDeployment(): Promise<this>;

  interface: Groth16ZkAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PROD_PROOF_MIN_LEN: TypedContractMethod<[], [bigint], "view">;

  expectedProofLength: TypedContractMethod<[], [bigint], "view">;

  policyHashPinned: TypedContractMethod<[], [string], "view">;

  programVKeyPinned: TypedContractMethod<[], [string], "view">;

  proofSystemId: TypedContractMethod<[], [bigint], "view">;

  verifierAddress: TypedContractMethod<[], [string], "view">;

  "verify(bytes,bytes32[])": TypedContractMethod<
    [proof: BytesLike, arg1: BytesLike[]],
    [boolean],
    "view"
  >;

  "verify(bytes,bytes)": TypedContractMethod<
    [proof: BytesLike, publicInputs: BytesLike],
    [
      [boolean, string, string, string, string] & {
        valid: boolean;
        stfCommitment: string;
        programVKey: string;
        policyHash: string;
        proverSetDigest: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PROD_PROOF_MIN_LEN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "expectedProofLength"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "policyHashPinned"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "programVKeyPinned"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proofSystemId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifierAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verify(bytes,bytes32[])"
  ): TypedContractMethod<
    [proof: BytesLike, arg1: BytesLike[]],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "verify(bytes,bytes)"
  ): TypedContractMethod<
    [proof: BytesLike, publicInputs: BytesLike],
    [
      [boolean, string, string, string, string] & {
        valid: boolean;
        stfCommitment: string;
        programVKey: string;
        policyHash: string;
        proverSetDigest: string;
      }
    ],
    "view"
  >;

  filters: {};
}
