/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IProofRouterInterface extends Interface {
  getFunction(
    nameOrSignature: "isSupported" | "routeProofAggregated"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isSupported",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "routeProofAggregated",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "isSupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "routeProofAggregated",
    data: BytesLike
  ): Result;
}

export interface IProofRouter extends BaseContract {
  connect(runner?: ContractRunner | null): IProofRouter;
  waitForDeployment(): Promise<this>;

  interface: IProofRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isSupported: TypedContractMethod<
    [proofSystemId: BigNumberish],
    [boolean],
    "view"
  >;

  routeProofAggregated: TypedContractMethod<
    [proofSystemId: BigNumberish, proof: BytesLike, publicInputs: BytesLike],
    [
      [boolean, string, string, string, string] & {
        valid: boolean;
        stfCommitment: string;
        programVKey: string;
        policyHash: string;
        proverSetDigest: string;
      }
    ],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isSupported"
  ): TypedContractMethod<[proofSystemId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "routeProofAggregated"
  ): TypedContractMethod<
    [proofSystemId: BigNumberish, proof: BytesLike, publicInputs: BytesLike],
    [
      [boolean, string, string, string, string] & {
        valid: boolean;
        stfCommitment: string;
        programVKey: string;
        policyHash: string;
        proverSetDigest: string;
      }
    ],
    "nonpayable"
  >;

  filters: {};
}
