/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  MockPlonkVerifier,
  MockPlonkVerifierInterface,
} from "../../test/MockPlonkVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[24]",
        name: "",
        type: "uint256[24]",
      },
      {
        internalType: "uint256[2]",
        name: "",
        type: "uint256[2]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608080604052346013576086908160188239f35b5f80fdfe60808060405260043610156011575f80fd5b5f3560e01c63c0e9d81c146023575f80fd5b34604c57610340366003190112604c573661030411604c573661034411604c5780600160209252f35b5f80fdfea264697066735822122018c854f78e1227644008c7f9cc06ea8c04e62356e0fec004d2dddc1e1000005f64736f6c63430008220033";

type MockPlonkVerifierConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockPlonkVerifierConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockPlonkVerifier__factory extends ContractFactory {
  constructor(...args: MockPlonkVerifierConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockPlonkVerifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockPlonkVerifier__factory {
    return super.connect(runner) as MockPlonkVerifier__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockPlonkVerifierInterface {
    return new Interface(_abi) as MockPlonkVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockPlonkVerifier {
    return new Contract(address, _abi, runner) as unknown as MockPlonkVerifier;
  }
}
