/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "BlobKzgVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BlobKzgVerifier__factory>;
    getContractFactory(
      name: "BlobSubmission",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BlobSubmission__factory>;
    getContractFactory(
      name: "BlobVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BlobVerifier__factory>;
    getContractFactory(
      name: "BlobVerifierHarness",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BlobVerifierHarness__factory>;
    getContractFactory(
      name: "IBlobSubmission",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBlobSubmission__factory>;
    getContractFactory(
      name: "IZkAggregatorVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IZkAggregatorVerifier__factory>;
    getContractFactory(
      name: "MockGroth16Verifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockGroth16Verifier__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "WorldlineCompat",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WorldlineCompat__factory>;
    getContractFactory(
      name: "WorldlineFinalizer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WorldlineFinalizer__factory>;
    getContractFactory(
      name: "WorldlineOutputsRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WorldlineOutputsRegistry__factory>;
    getContractFactory(
      name: "WorldlineRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WorldlineRegistry__factory>;
    getContractFactory(
      name: "Groth16Verifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Groth16Verifier__factory>;
    getContractFactory(
      name: "Groth16ZkAdapter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Groth16ZkAdapter__factory>;

    getContractAt(
      name: "BlobKzgVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BlobKzgVerifier>;
    getContractAt(
      name: "BlobSubmission",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BlobSubmission>;
    getContractAt(
      name: "BlobVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BlobVerifier>;
    getContractAt(
      name: "BlobVerifierHarness",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BlobVerifierHarness>;
    getContractAt(
      name: "IBlobSubmission",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBlobSubmission>;
    getContractAt(
      name: "IZkAggregatorVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IZkAggregatorVerifier>;
    getContractAt(
      name: "MockGroth16Verifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockGroth16Verifier>;
    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "WorldlineCompat",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.WorldlineCompat>;
    getContractAt(
      name: "WorldlineFinalizer",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.WorldlineFinalizer>;
    getContractAt(
      name: "WorldlineOutputsRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.WorldlineOutputsRegistry>;
    getContractAt(
      name: "WorldlineRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.WorldlineRegistry>;
    getContractAt(
      name: "Groth16Verifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Groth16Verifier>;
    getContractAt(
      name: "Groth16ZkAdapter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Groth16ZkAdapter>;

    deployContract(
      name: "BlobKzgVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BlobKzgVerifier>;
    deployContract(
      name: "BlobSubmission",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BlobSubmission>;
    deployContract(
      name: "BlobVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BlobVerifier>;
    deployContract(
      name: "BlobVerifierHarness",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BlobVerifierHarness>;
    deployContract(
      name: "IBlobSubmission",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBlobSubmission>;
    deployContract(
      name: "IZkAggregatorVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IZkAggregatorVerifier>;
    deployContract(
      name: "MockGroth16Verifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockGroth16Verifier>;
    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "WorldlineCompat",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WorldlineCompat>;
    deployContract(
      name: "WorldlineFinalizer",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WorldlineFinalizer>;
    deployContract(
      name: "WorldlineOutputsRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WorldlineOutputsRegistry>;
    deployContract(
      name: "WorldlineRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WorldlineRegistry>;
    deployContract(
      name: "Groth16Verifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Groth16Verifier>;
    deployContract(
      name: "Groth16ZkAdapter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Groth16ZkAdapter>;

    deployContract(
      name: "BlobKzgVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BlobKzgVerifier>;
    deployContract(
      name: "BlobSubmission",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BlobSubmission>;
    deployContract(
      name: "BlobVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BlobVerifier>;
    deployContract(
      name: "BlobVerifierHarness",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BlobVerifierHarness>;
    deployContract(
      name: "IBlobSubmission",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBlobSubmission>;
    deployContract(
      name: "IZkAggregatorVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IZkAggregatorVerifier>;
    deployContract(
      name: "MockGroth16Verifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockGroth16Verifier>;
    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "WorldlineCompat",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WorldlineCompat>;
    deployContract(
      name: "WorldlineFinalizer",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WorldlineFinalizer>;
    deployContract(
      name: "WorldlineOutputsRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WorldlineOutputsRegistry>;
    deployContract(
      name: "WorldlineRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WorldlineRegistry>;
    deployContract(
      name: "Groth16Verifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Groth16Verifier>;
    deployContract(
      name: "Groth16ZkAdapter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Groth16ZkAdapter>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
