/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod
} from "./common";

export declare namespace WorldlineOutputsRegistry {
  export type OutputEntryStruct = {
    programVKey: BytesLike;
    policyHash: BytesLike;
    oracle: AddressLike;
    active: boolean;
  };

  export type OutputEntryStructOutput = [
    programVKey: string,
    policyHash: string,
    oracle: string,
    active: boolean
  ] & {
    programVKey: string;
    policyHash: string;
    oracle: string;
    active: boolean;
  };
}

export interface WorldlineOutputsRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activate"
      | "activeEntries"
      | "domainKey"
      | "getActiveEntry"
      | "isActive"
      | "minTimelock"
      | "owner"
      | "pendingEntries"
      | "schedule"
      | "setMinTimelock"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OutputActivated" | "OutputScheduled" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "activate", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "activeEntries", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "domainKey", values: [BytesLike, BytesLike]): string;
  encodeFunctionData(functionFragment: "getActiveEntry", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "isActive", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "minTimelock", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pendingEntries", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "schedule",
    values: [BytesLike, BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setMinTimelock", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "transferOwnership", values: [AddressLike]): string;

  decodeFunctionResult(functionFragment: "activate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "activeEntries", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "domainKey", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getActiveEntry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "minTimelock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pendingEntries", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "schedule", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setMinTimelock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transferOwnership", data: BytesLike): Result;
}

export namespace OutputActivatedEvent {
  export type InputTuple = [
    domainKey: BytesLike,
    programVKey: BytesLike,
    policyHash: BytesLike,
    oracle: AddressLike
  ];
  export type OutputTuple = [
    domainKey: string,
    programVKey: string,
    policyHash: string,
    oracle: string
  ];
  export interface OutputObject {
    domainKey: string;
    programVKey: string;
    policyHash: string;
    oracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OutputScheduledEvent {
  export type InputTuple = [
    domainKey: BytesLike,
    programVKey: BytesLike,
    policyHash: BytesLike,
    oracle: AddressLike,
    activationTime: BigNumberish
  ];
  export type OutputTuple = [
    domainKey: string,
    programVKey: string,
    policyHash: string,
    oracle: string,
    activationTime: bigint
  ];
  export interface OutputObject {
    domainKey: string;
    programVKey: string;
    policyHash: string;
    oracle: string;
    activationTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WorldlineOutputsRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): WorldlineOutputsRegistry;
  waitForDeployment(): Promise<this>;

  interface: WorldlineOutputsRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  activate: TypedContractMethod<[_domainKey: BytesLike], [void], "nonpayable">;

  activeEntries: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, boolean] & {
        programVKey: string;
        policyHash: string;
        oracle: string;
        active: boolean;
      }
    ],
    "view"
  >;

  domainKey: TypedContractMethod<[chainIdHash: BytesLike, domainTag: BytesLike], [string], "view">;

  getActiveEntry: TypedContractMethod<
    [_domainKey: BytesLike],
    [WorldlineOutputsRegistry.OutputEntryStructOutput],
    "view"
  >;

  isActive: TypedContractMethod<[_domainKey: BytesLike], [boolean], "view">;

  minTimelock: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingEntries: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, boolean] & {
        programVKey: string;
        policyHash: string;
        oracle: string;
        activationTime: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  schedule: TypedContractMethod<
    [_domainKey: BytesLike, programVKey: BytesLike, policyHash: BytesLike, oracle: AddressLike],
    [void],
    "nonpayable"
  >;

  setMinTimelock: TypedContractMethod<[_minTimelock: BigNumberish], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(
    nameOrSignature: "activate"
  ): TypedContractMethod<[_domainKey: BytesLike], [void], "nonpayable">;
  getFunction(nameOrSignature: "activeEntries"): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, boolean] & {
        programVKey: string;
        policyHash: string;
        oracle: string;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "domainKey"
  ): TypedContractMethod<[chainIdHash: BytesLike, domainTag: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getActiveEntry"
  ): TypedContractMethod<
    [_domainKey: BytesLike],
    [WorldlineOutputsRegistry.OutputEntryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<[_domainKey: BytesLike], [boolean], "view">;
  getFunction(nameOrSignature: "minTimelock"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "owner"): TypedContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "pendingEntries"): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, boolean] & {
        programVKey: string;
        policyHash: string;
        oracle: string;
        activationTime: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "schedule"
  ): TypedContractMethod<
    [_domainKey: BytesLike, programVKey: BytesLike, policyHash: BytesLike, oracle: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMinTimelock"
  ): TypedContractMethod<[_minTimelock: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OutputActivated"
  ): TypedContractEvent<
    OutputActivatedEvent.InputTuple,
    OutputActivatedEvent.OutputTuple,
    OutputActivatedEvent.OutputObject
  >;
  getEvent(
    key: "OutputScheduled"
  ): TypedContractEvent<
    OutputScheduledEvent.InputTuple,
    OutputScheduledEvent.OutputTuple,
    OutputScheduledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "OutputActivated(bytes32,bytes32,bytes32,address)": TypedContractEvent<
      OutputActivatedEvent.InputTuple,
      OutputActivatedEvent.OutputTuple,
      OutputActivatedEvent.OutputObject
    >;
    OutputActivated: TypedContractEvent<
      OutputActivatedEvent.InputTuple,
      OutputActivatedEvent.OutputTuple,
      OutputActivatedEvent.OutputObject
    >;

    "OutputScheduled(bytes32,bytes32,bytes32,address,uint256)": TypedContractEvent<
      OutputScheduledEvent.InputTuple,
      OutputScheduledEvent.OutputTuple,
      OutputScheduledEvent.OutputObject
    >;
    OutputScheduled: TypedContractEvent<
      OutputScheduledEvent.InputTuple,
      OutputScheduledEvent.OutputTuple,
      OutputScheduledEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
