/**
 * Halo2 real verifier integration tests.
 *
 * Exercises the full cryptographic round-trip: real KZG proof → real
 * Halo2Verifier on-chain pairing check → adapter extraction → acceptance.
 *
 * Uses a deterministic proof fixture generated by:
 *   cargo run -p worldline-halo2-circuit --example generate_fixture
 *
 * The fixture contains a genuine Halo2 KZG proof over the WorldlineSTF circuit
 * with canonical test inputs. Unlike the mock-based halo2.test.ts, the pairing
 * check executes for real here.
 */

import { expect } from "chai";
import { ethers, upgrades } from "hardhat";
import * as fs from "fs";
import * as path from "path";
import {
  DOMAIN,
  PROGRAM_VKEY,
  POLICY_HASH,
  MAX_ACCEPTANCE_DELAY,
  GENESIS_L2_BLOCK,
  enablePermissionless,
  findEventLog
} from "./deployment-fixtures";

interface Halo2Fixture {
  publicOutputs: {
    stfCommitment: string;
    proverSetDigest: string;
  };
  proof: {
    rawBytes: string;
    lengthBytes: number;
  };
}

function loadHalo2Fixture(): Halo2Fixture {
  const fixturePath = path.join(__dirname, "../fixtures/halo2-proof-fixture.json");
  return JSON.parse(fs.readFileSync(fixturePath, "utf-8"));
}

/**
 * Encode a Halo2 proof envelope using real proof bytes from the fixture.
 */
function encodeRealHalo2Proof(fixture: Halo2Fixture): string {
  return ethers.AbiCoder.defaultAbiCoder().encode(
    ["bytes", "uint256", "uint256"],
    [
      fixture.proof.rawBytes,
      BigInt(fixture.publicOutputs.stfCommitment),
      BigInt(fixture.publicOutputs.proverSetDigest)
    ]
  );
}

/**
 * Build publicInputs where word 0 = the real fixture's stfCommitment.
 * This ensures the finalizer's StfMismatch check passes with the real proof.
 *
 * We set submissionBinding (word 7) = keccak256(abi.encode(words 1-6)) as normal,
 * but override word 0 to the real Poseidon-based stfCommitment from the fixture.
 */
function encodePublicInputsWithRealStf(
  l2Start: bigint,
  l2End: bigint,
  windowCloseTimestamp: bigint,
  realStfCommitment: string,
  domain: string = DOMAIN
): string {
  const submissionBinding = ethers.keccak256(
    ethers.AbiCoder.defaultAbiCoder().encode(
      ["uint256", "uint256", "bytes32", "bytes32", "bytes32", "uint256"],
      [l2Start, l2End, ethers.ZeroHash, ethers.ZeroHash, domain, windowCloseTimestamp]
    )
  );
  return ethers.AbiCoder.defaultAbiCoder().encode(
    ["bytes32", "uint256", "uint256", "bytes32", "bytes32", "bytes32", "uint256", "bytes32"],
    [
      realStfCommitment,
      l2Start,
      l2End,
      ethers.ZeroHash,
      ethers.ZeroHash,
      domain,
      windowCloseTimestamp,
      submissionBinding
    ]
  );
}

describe("Halo2 real verifier integration", function () {
  this.timeout(120_000);

  let fixture: Halo2Fixture;

  before(function () {
    fixture = loadHalo2Fixture();
  });

  // ── 1. Real Halo2Verifier accepts genuine KZG proof ─────────────────────

  it("real Halo2Verifier accepts a genuine KZG proof via adapter", async function () {
    const [owner] = await ethers.getSigners();

    // Deploy real verifier (not mock)
    const Verifier = await ethers.getContractFactory("Halo2Verifier", owner);
    const verifier = await Verifier.deploy();
    await verifier.waitForDeployment();

    // Deploy adapter wired to real verifier
    const Adapter = await ethers.getContractFactory("Halo2ZkAdapter", owner);
    const adapter = await Adapter.deploy(await verifier.getAddress(), PROGRAM_VKEY, POLICY_HASH);
    await adapter.waitForDeployment();

    // Encode real proof envelope
    const envelope = encodeRealHalo2Proof(fixture);

    // Call aggregator-path verify
    const result = await adapter.getFunction("verify(bytes,bytes)").staticCall(envelope, "0x");
    expect(result.valid).to.equal(true, "Real verifier must accept genuine proof");
    expect(result.stfCommitment).to.equal(fixture.publicOutputs.stfCommitment);
    expect(result.proverSetDigest).to.equal(fixture.publicOutputs.proverSetDigest);
    expect(result.programVKey).to.equal(PROGRAM_VKEY);
    expect(result.policyHash).to.equal(POLICY_HASH);
  });

  // ── 2. Real Halo2Verifier rejects corrupted proof ───────────────────────

  it("real Halo2Verifier rejects a corrupted proof via adapter", async function () {
    const [owner] = await ethers.getSigners();

    const Verifier = await ethers.getContractFactory("Halo2Verifier", owner);
    const verifier = await Verifier.deploy();
    await verifier.waitForDeployment();

    const Adapter = await ethers.getContractFactory("Halo2ZkAdapter", owner);
    const adapter = await Adapter.deploy(await verifier.getAddress(), PROGRAM_VKEY, POLICY_HASH);
    await adapter.waitForDeployment();

    // Corrupt the proof: flip a byte in the middle
    const rawBytes = ethers.getBytes(fixture.proof.rawBytes);
    const corrupted = new Uint8Array(rawBytes);
    corrupted[100] ^= 0xff;

    const envelope = ethers.AbiCoder.defaultAbiCoder().encode(
      ["bytes", "uint256", "uint256"],
      [
        corrupted,
        BigInt(fixture.publicOutputs.stfCommitment),
        BigInt(fixture.publicOutputs.proverSetDigest)
      ]
    );

    // Pairing check should fail — adapter reverts with ProofInvalid
    await expect(adapter.getFunction("verify(bytes,bytes)").staticCall(envelope, "0x")).to.be
      .reverted;
  });

  // ── 3. Real Halo2Verifier rejects wrong public instances ────────────────

  it("real Halo2Verifier rejects proof with wrong stfCommitment", async function () {
    const [owner] = await ethers.getSigners();

    const Verifier = await ethers.getContractFactory("Halo2Verifier", owner);
    const verifier = await Verifier.deploy();
    await verifier.waitForDeployment();

    const Adapter = await ethers.getContractFactory("Halo2ZkAdapter", owner);
    const adapter = await Adapter.deploy(await verifier.getAddress(), PROGRAM_VKEY, POLICY_HASH);
    await adapter.waitForDeployment();

    // Use correct proof bytes but flip a bit in stfCommitment
    const wrongStf = BigInt(fixture.publicOutputs.stfCommitment) ^ 1n;
    const envelope = ethers.AbiCoder.defaultAbiCoder().encode(
      ["bytes", "uint256", "uint256"],
      [fixture.proof.rawBytes, wrongStf, BigInt(fixture.publicOutputs.proverSetDigest)]
    );

    await expect(adapter.getFunction("verify(bytes,bytes)").staticCall(envelope, "0x")).to.be
      .reverted;
  });

  // ── 4. Full stack: real proof through router → finalizer ────────────────

  it("full stack submission with real Halo2 proof through router and finalizer", async function () {
    const [owner] = await ethers.getSigners();

    // Deploy real Halo2 verifier + adapter
    const Verifier = await ethers.getContractFactory("Halo2Verifier", owner);
    const verifier = await Verifier.deploy();
    await verifier.waitForDeployment();

    const Adapter = await ethers.getContractFactory("Halo2ZkAdapter", owner);
    const adapter = await Adapter.deploy(await verifier.getAddress(), PROGRAM_VKEY, POLICY_HASH);
    await adapter.waitForDeployment();

    // Deploy router and register Halo2 adapter at ID=3
    const Router = await ethers.getContractFactory("ProofRouter", owner);
    const router = await upgrades.deployProxy(Router, [], { kind: "uups" });
    await router.waitForDeployment();
    await (await (router as any).registerAdapter(3, await adapter.getAddress())).wait();

    // Deploy finalizer wired to the adapter (direct, not routed initially)
    const Finalizer = await ethers.getContractFactory("WorldlineFinalizer", owner);
    const finalizer = await upgrades.deployProxy(
      Finalizer,
      [
        await adapter.getAddress(),
        DOMAIN,
        MAX_ACCEPTANCE_DELAY,
        GENESIS_L2_BLOCK,
        ethers.ZeroAddress
      ],
      { kind: "uups", initializer: "initialize" }
    );
    await finalizer.waitForDeployment();

    // Wire router and enable permissionless
    await (await (finalizer as any).setProofRouter(await router.getAddress())).wait();
    await enablePermissionless(finalizer);

    // Build the submission
    const l2Start = GENESIS_L2_BLOCK;
    const l2End = 100n;
    const block = await ethers.provider.getBlock("latest");
    const windowCloseTimestamp = BigInt(block!.timestamp) + 7200n;

    const proof = encodeRealHalo2Proof(fixture);
    const publicInputs = encodePublicInputsWithRealStf(
      l2Start,
      l2End,
      windowCloseTimestamp,
      fixture.publicOutputs.stfCommitment,
      DOMAIN
    );

    // Submit via routed path (proofSystemId=3 = Halo2)
    const tx = await (finalizer as any).submitZkValidityProofRouted(3, proof, publicInputs);
    const receipt = await tx.wait();

    // Verify the ZkProofAccepted event
    const iface = (finalizer as any).interface;
    const event = findEventLog(receipt, iface, "ZkProofAccepted");
    expect(event).to.not.be.null;
    expect(event.args.windowIndex).to.equal(0n);
  });

  // ── 5. IZkAdapter thin verify path works with real proof ────────────────

  it("IZkAdapter thin verify path accepts real proof", async function () {
    const [owner] = await ethers.getSigners();

    const Verifier = await ethers.getContractFactory("Halo2Verifier", owner);
    const verifier = await Verifier.deploy();
    await verifier.waitForDeployment();

    const Adapter = await ethers.getContractFactory("Halo2ZkAdapter", owner);
    const adapter = await Adapter.deploy(await verifier.getAddress(), PROGRAM_VKEY, POLICY_HASH);
    await adapter.waitForDeployment();

    const envelope = encodeRealHalo2Proof(fixture);

    // Call through IZkAdapter.verify(bytes,bytes32[])
    const valid = await adapter.getFunction("verify(bytes,bytes32[])").staticCall(envelope, []);
    expect(valid).to.equal(true);
  });
});
