services:
  hardhat-node:
    build:
      context: ..
      dockerfile: devnet/Dockerfile
    ports:
      - "8545:8545"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 5s
      timeout: 3s
      retries: 10
